# Generated by Django 4.1.2 on 2023-02-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("pid", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("catname", models.CharField(max_length=50)),
                ("subcatname", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("price", models.CharField(max_length=10)),
                ("piconname", models.CharField(max_length=100)),
                ("info", models.CharField(max_length=50)),
            ],
        ),
    ]
