# Generated by Django 4.1.2 on 2023-02-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funds",
            fields=[
                ("txnid", models.AutoField(primary_key=True, serialize=False)),
                ("uid", models.CharField(max_length=50)),
                ("amt", models.IntegerField()),
                ("info", models.CharField(max_length=50)),
            ],
        ),
    ]
